language: node_js
node_js:
  - "6"
  - "5"
  - "4"
# before_script:
#  - npm install
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test
  - npm run cover
  - codecov
after_script:
  - bash <(curl -s https://codecov.io/bash)