language: node_js
node_js:
  - "6"
  - "5"
  - "4"
# before_script:
#  - npm install
script:
  - npm run test
  - npm run cover
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - bash <(curl -s https://codecov.io/bash)